[package]
name = "session-protobuf-types"
version = "0.1.0"
edition = "2021"
description = "Generated protobuf types using prost"

[dependencies]
prost = "0.14"

[build-dependencies]
prost-build = "0.14"
