[package]
name = "protobuf-types"
version = "0.1.0"
edition = "2021"
description = "Generated protobuf types with minimal dependencies"

[dependencies]
protobuf = "3.4"

[build-dependencies]
protobuf-codegen = "3.4"

[[bin]]
name = "generate"
path = "src/main.rs"
required-features = []
