name: Test Build (Act Compatible)

on:
  workflow_dispatch:
  push:
    branches: [ test-* ]

jobs:
  test-build-linux:
    name: Test Build on Linux
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Make build script executable
      run: chmod +x build.sh

    - name: Test build script syntax
      run: |
        echo "Testing build script syntax..."
        bash -n build.sh
        echo "✅ Build script syntax is valid!"

    - name: Check protoc binaries
      run: |
        echo "=== Available protoc binaries ==="
        ls -la protoc-* || echo "No protoc directories found"
        
        # Check if Linux protoc exists and is executable
        if [ -f "protoc-32.1-linux-x86_64/bin/protoc" ]; then
          echo "✅ Linux protoc binary found"
          ls -la protoc-32.1-linux-x86_64/bin/protoc
          echo "Testing protoc version:"
          ./protoc-32.1-linux-x86_64/bin/protoc --version || echo "Could not run protoc"
        else
          echo "❌ Linux protoc binary not found"
        fi

    - name: Check proto files
      run: |
        echo "=== Proto Files ==="
        if [ -d "proto" ]; then
          find proto -name "*.proto" -type f
          echo ""
          echo "Proto file contents:"
          for proto in proto/*.proto; do
            if [ -f "$proto" ]; then
              echo "--- $proto ---"
              head -10 "$proto"
              echo ""
            fi
          done
        else
          echo "No proto directory found"
        fi

    - name: Run build script
      run: |
        echo "Running build script..."
        ./build.sh

    - name: Verify generated files
      run: |
        echo "=== Generated Files ==="
        echo "C++ files:"
        find generated/cpp -name "*.pb.*" -type f 2>/dev/null || echo "No C++ files generated"
        
        echo "Python files:"
        find generated/python -name "*_pb2.py" -type f 2>/dev/null || echo "No Python files generated"
        
        echo "Rust files:"
        ls -la generated/rust/ 2>/dev/null || echo "No Rust directory found"
        
        echo "Archives:"
        ls -la *.tar.gz 2>/dev/null || echo "No archives found"

    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      with:
        name: protobuf-test-artifacts
        path: |
          *.tar.gz
          generated/
        retention-days: 1
