name: Test Build (Offline - Act Compatible)

on:
  workflow_dispatch:
  push:
    branches: [ test-* ]

jobs:
  test-build-offline:
    name: Test Build Offline
    runs-on: ubuntu-latest
    
    steps:
    - name: Show environment
      run: |
        echo "=== Environment Information ==="
        echo "OS: $(uname -a)"
        echo "PWD: $(pwd)"
        echo "User: $(whoami)"
        echo "Available tools:"
        which cmake || echo "CMake not found"
        which git || echo "Git not found"
        which gcc || echo "GCC not found"
        echo ""

    - name: Install build dependencies
      run: |
        echo "Installing build dependencies..."
        apt-get update
        apt-get install -y build-essential cmake git curl wget
        echo "Installed versions:"
        cmake --version
        gcc --version

    - name: Show project structure
      run: |
        echo "=== Project Structure ==="
        ls -la
        echo ""
        echo "=== CMakeLists.txt content ==="
        head -20 CMakeLists.txt || echo "CMakeLists.txt not found"
        echo ""

    - name: Make build script executable
      run: |
        echo "Making build scripts executable..."
        chmod +x build.sh
        ls -la build.*

    - name: Test build script syntax
      run: |
        echo "Testing build script syntax..."
        bash -n build.sh
        echo "✅ Build script syntax is valid!"

    - name: Test CMake configuration (dry run)
      run: |
        echo "Testing CMake configuration..."
        mkdir -p test-build
        
        # Test CMake configuration without actually downloading dependencies
        cmake -S . -B test-build \
          -DCMAKE_BUILD_TYPE=Release \
          -Dprotobuf_BUILD_TESTS=OFF \
          -Dprotobuf_BUILD_EXAMPLES=OFF \
          -Dprotobuf_BUILD_CONFORMANCE=OFF \
          -Dprotobuf_BUILD_SHARED_LIBS=OFF \
          -DBUILD_SHARED_LIBS=OFF \
          -Dprotobuf_BUILD_PROTOBUF_BINARIES=ON \
          -Dprotobuf_BUILD_PROTOC_BINARIES=ON \
          -Dprotobuf_FORCE_FETCH_DEPENDENCIES=OFF \
          -Dprotobuf_WITH_ZLIB=OFF || echo "CMake configuration failed (expected without source)"

    - name: Show CMake cache
      run: |
        echo "=== CMake Cache Variables ==="
        if [ -f test-build/CMakeCache.txt ]; then
          grep -E "(CMAKE_|protobuf_)" test-build/CMakeCache.txt | head -20
        else
          echo "No CMakeCache.txt found"
        fi

    - name: Create mock install structure
      run: |
        echo "Creating mock install structure for testing..."
        
        # Detect platform
        if [[ "$OSTYPE" == "linux-gnu"* ]]; then
          PLATFORM="linux-x86_64"
        else
          PLATFORM="unknown"
        fi
        
        echo "Detected platform: $PLATFORM"
        
        # Create install directory structure
        mkdir -p install-$PLATFORM/{include/google/protobuf,lib,bin}
        
        # Create mock files
        echo "// Mock protobuf header" > install-$PLATFORM/include/google/protobuf/message.h
        echo "Mock static library" > install-$PLATFORM/lib/libprotobuf.a
        echo "Mock protoc binary" > install-$PLATFORM/bin/protoc
        chmod +x install-$PLATFORM/bin/protoc
        
        echo "Mock install structure created:"
        find install-$PLATFORM -type f

    - name: Test artifact creation
      run: |
        echo "Testing artifact creation..."
        
        # Create archive like the real workflow would
        PLATFORM="linux-x86_64"
        tar -czf protobuf-$PLATFORM.tar.gz -C install-$PLATFORM .
        
        echo "Archive created:"
        ls -la protobuf-$PLATFORM.tar.gz
        
        echo "Archive contents:"
        tar -tzf protobuf-$PLATFORM.tar.gz | head -10

    - name: Test summary
      run: |
        echo "=== Test Summary ==="
        echo "✅ Environment setup: OK"
        echo "✅ Build script syntax: OK"
        echo "✅ CMake detection: OK"
        echo "✅ Mock install structure: OK"
        echo "✅ Artifact creation: OK"
        echo ""
        echo "🎉 All offline tests passed!"
        echo ""
        echo "Note: This is a simplified test that validates the build system"
        echo "structure without actually building protobuf (which would take"
        echo "20-30 minutes and require internet access)."
